
default: &default
  adapter: postgresql
  database: nome_do_banco
  username: nome_do_usuario
  password: senha
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nome_do_banco

test:
  <<: *default
  database: nome_do_banco

production:
  <<: *default
  database: nome_do_banco
  url: <%= ENV['POSTGRES_URL'] %>
